version: 2.1

commands:
  install_asdf:
    steps:
      - run:
          name: install asdf
          command: |
            git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.0
            echo 'export ASDF_DIR="$HOME/.asdf"' >> "$BASH_ENV"
            echo '. "$HOME/.asdf/asdf.sh"' >> "$BASH_ENV"

  asdf_plugin_test:
    steps:
      - run:
          name: test
          command: |
            eval "PLUGIN_DIR=${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}"
            # Have to expand `~` manually.  CircleCI does not use the
            # canonical path.
            #
            # https://discuss.circleci.com/t/circle-working-directory-doesnt-expand/17007/5
            asdf plugin test zls "$PLUGIN_DIR" --asdf-plugin-gitref "$CIRCLE_SHA1" "zls --version" # DevSkim: ignore DS126858
            #
            # Fix false positive from DevSkim.
            #
            # `CIRCLE_SHA1` is just a variable, not an algorithm.
            #
            # https://github.com/microsoft/DevSkim/wiki/Suppressions
            # https://github.com/Microsoft/DevSkim/blob/main/guidance/DS126858.md
            # https://circleci.com/docs/variables/#built-in-environment-variables

jobs:
  plugin_test:
    docker:
      - image: cimg/base:current
        # checkov:skip=CKV_CIRCLECIPIPELINES_2:prefer mutable but stable tags
    steps:
      - checkout
      - install_asdf
      - asdf_plugin_test

  plugin_test_macos:
    macos:
      xcode: 15.0.0
    steps:
      - checkout
      - run:
          name: install GNU tar
          command: |
            brew update
            brew install gnu-tar
            echo "export PATH=\"$(brew --prefix)/opt/gnu-tar/libexec/gnubin\":\"\$PATH\"" >> "$BASH_ENV"
            # https://circleci.com/docs/env-vars/#parameters-and-bash-environment
      - install_asdf
      - asdf_plugin_test

workflows:
  Build:
    jobs:
      - plugin_test
      - plugin_test_macos
